version: "2.4"

services:
  redis:
    image: redis:alpine

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql/data

  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "5000:80"
    depends_on:
      - redis

  result:
    build:
      context: .
      target: dev
    ports:
      - "5001:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  worker:
    image: bretfisher/examplevotingapp_worker:java
    depends_on:
      - redis
      - db

volumes:
  db-data:
